export default () => ({ 
    token:null,
    user:null,
    partner:null,
    subscribeNetwork:null,
    subscribeProvider:null,
    subscribeAcademy:null,
    subscribeIncubator:null,
    isSubscribeNetwork:false,
    isSubscribeProvider:false,
    isSubscribeAcademy:false,
    isSubscribeIncubator:false,
    isProvider:false,
    academyRole:null,
    isInstructor:false,
    isConsultant:false,
 })