name: Build

on:
  push:
    branches:
      - riadiat/2 # Adjust the branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Adjust the Node.js version if needed

      - name: Install dependencies
        run: npm install # Adjust the package manager command if needed

      - name: Build project
        run: npm run build # Adjust the build command if needed
